### ISSUE TITLE
Fix broken wheel build

### ISSUE THREAD

**Issue by gtback** [oasis-open/cti-pattern-validator#18]
Something unexpected happened when I uploaded stix2_patterns-0.3.0-py2.py3-none-any.whl to PyPI. That build required *both* antlr4-python2-runtime and antlr4-python3-runtime, causing installs to break. I took down the wheel, so users should still get 0.2.2, but I need to figure out what is causing setuptools/wheel to put incorrect metadata into the wheel.

**Comment by clenk** [comment]
Looks like an issue with wheel: https://bitbucket.org/pypa/wheel/issues/181/bdist_wheel-silently-discards-pep-508

**Comment by gtback** [comment]
It seems like there's a lot of work going on in the setuptools repo to handle situations like this.
