### ISSUE TITLE
stix validator does not handle list of stix objects in a file

### ISSUE THREAD

**Issue by jmgnc** [oasis-open/cti-pattern-validator#27]
If you attempt to validate a file which contains a list of stix objects (for testing w/ the stix pattern matcher code), you cannot, and will get the error:
[X] Fatal Error: Input must be an object with a 'type' property.

Please support files w/ a list of stix objects, validating each object in the list.

Thanks.

**Comment by gtback** [comment]
@jmgnc, is this an issue with the pattern validator or the STIX validator?

**Comment by jmgnc** [comment]
This is an issue w/ the STIX validator, sorry wrong git repo.  I've refiled w/ the correct one at: https://github.com/oasis-open/cti-stix-validator/issues/31

**Comment by gtback** [comment]
Thanks, @jmgnc
