### ISSUE TITLE
ANTLRv4 grammar syntax error

### ISSUE THREAD

**Issue by ShakedH** [oasis-open/cti-pattern-validator#4]
Hello,

I'm using the ANTLR grammar to parse stix patterns but there seems to be a problem in the grammar.
The error I'm getting is:
error(156): STIXPattern.g4:233:7: invalid escape sequence

**Comment by gtback** [comment]
Thanks, @ShakedH. Am I correct in guessing this happened with ANTLR 4.6? If so, I'm guessing it's the same thing that was changed in oasis-open/cti-pattern-matcher#14. Should be an easy fix.

**Comment by gtback** [comment]
FYI, I reverted the generated grammar files in this repo to the version produced by ANTLR 4.5.3, until #5 is fixed. This problem should not recur, since the underlying grammar has been updated (and should work with both 4.5.3 and 4.6).
