### ISSUE TITLE
Repeat Negative Times

### ISSUE THREAD

**Issue by varnerac** [oasis-open/cti-pattern-validator#41]
```
$ validate-patterns
Enter a pattern to validate: [ipv4-addr:value = '198.51.100.1/32'] REPEATS -5 TIMES

PASS: [ipv4-addr:value = '198.51.100.1/32'] REPEATS -5 TIMES
```

I don't think something should be allowed to repeat a negative number of times.

**Comment by gtback** [comment]
Thanks for opening this, @varnerac and sorry for not seeing it right away. I'll need to check whether this is technically allowed by the spec; if so, we probably shouldn't invalidate it here. I agree that the pattern doesn't make sense semantically :-)

**Comment by gtback** [comment]
@varnerac This should be fixed now, but if not, feel free to reopen.
