### ISSUE TITLE
Tighten Timestamp Validation

### ISSUE THREAD

**Issue by varnerac** [oasis-open/cti-pattern-validator#42]
The validation of timestamp literals should be tightened to ensure it meets the requirements in STIX 2.0 and the portion RFC 3339 it implements.

```
$ validate-patterns
Enter a pattern to validate: [x_whatever:detected == t'2457-73-22T32:81:84.1Z']

PASS: [x_whatever:detected == t'2457-73-22T32:81:84.1Z']
```

**Comment by gtback** [comment]
Thanks @varnerac and sorry for not seeing it right away. I'll hopefully have a chance to look into it soon.

**Comment by gtback** [comment]
@varnerac This should be fixed now, but if not, feel free to reopen.
