### ISSUE TITLE
Bad Pattern for Binary Literals

### ISSUE THREAD

**Issue by varnerac** [oasis-open/cti-pattern-validator#43]
From latest `pip` installed version:

```
Enter a pattern to validate: [ qq  : dt  . DI   NOt < b'====']              

PASS: [ qq  : dt  . DI   NOt < b'====']
```

`====` is not a valid Base64 literal

**Comment by gtback** [comment]
Thanks, @varnerac. We'll have to see the best way to fix this.

**Comment by gtback** [comment]
@varnerac This should be fixed now, but if not, feel free to reopen.

**Comment by varnerac** [comment]
LGTM
