### ISSUE TITLE
Problems with single quotes in value field

### ISSUE THREAD

**Issue by wutdequack** [oasis-open/cti-pattern-validator#45]
I submitted this pattern to the validator `[windows-registry-value-type:data = 'connect('http://8.8.8.8')']`

The validator returned this error: `Error
[u"FAIL: Error found at line 1:46. mismatched input 'http' expecting ']'"]`

I suspected it was due to the single inverted commas in the value field of the pattern. I tried escaping the single inverted comma but to no avail. It was only through removing the single inverted commas in the value field that the pattern was successfully validated. 

Is there any fix for this? Any help will be much appreciated!

**Comment by chisholm** [comment]
"Inverted comma"... that's new :)  I think people usually call them "single quotes", or sometimes "apostrophes".  How did you escape them?  You should use backslashes, e.g.:

`[windows-registry-value-type:data = 'connect(\'http://8.8.8.8\')']`

**Comment by wutdequack** [comment]
Hahaha I see. My English is not that good, but it's great that you could understand what I meant. I think it is still very peculiar, as it can only work with a double escape like below. Is this supposed to be the case?
`[windows-registry-value-type:data = 'connect(\\'http://8.8.8.8\\')']`

**Comment by chisholm** [comment]
Did you paste your pattern from source code?  A programming language or other file format can impose its own, additional constraints.  E.g. backslashes inside string literals are treated specially by the Python interpreter.  If you don't double them (escape the escape character), the interpreter will think they're an embedded escape sequence and remove the backslash.

The pattern validator comes with a commandline script.  If you enter the pattern with single backslashes, it will validate.  For example (this is on Windows):

    C:\some\directory>validate-patterns
    Enter a pattern to validate: [windows-registry-value-type:data = 'connect(\'http://8.8.8.8\')']

    PASS: [windows-registry-value-type:data = 'connect(\'http://8.8.8.8\')']
    Enter a pattern to validate: ^Z

    PASSED: 1  patterns
    FAILED: 0  patterns

**Comment by wutdequack** [comment]
Ahhh I see. I think this could be the case. Thanks! Will close this issue for now (:
