### ISSUE TITLE
stix2-patterns incompatible with antlr4-python3-runtime>=4.8

### ISSUE THREAD

**Issue by Rafiot** [oasis-open/cti-pattern-validator#67]
antlr4-python3-runtime v4.8 was released the 2020-01-16 and using stix2-patterns with that version returns error messages.

**Comment by chisholm** [comment]
Yeah, the parser and runtime are mismatched in that case.  So we should change the dependency version spec to ==4.7.* maybe?

**Comment by Rafiot** [comment]
If there are no ways to make it compatible to both, you should pick one, yes.

I personally prefer use the latest one, but that's ultimately your call. Maybe 4.8 for the next release?
