### ISSUE TITLE
Validator passing indicator patterns with incorrect format

### ISSUE THREAD

**Issue by patrickmayer1120** [oasis-open/cti-pattern-validator#78]
According to STIX documentation the correct syntax for matching a windows registry key is as follows.

windows-registry-key:key    

The validator is accepting "windows-reg-key:key" which is incorrect syntax. 

Thank you for your helpful validator tool!

**Comment by clenk** [comment]
Hi @patrickmayer1120, thanks for the comment. The pattern validator only checks syntax and doesn't make sure object type or property names are defined in the STIX specification. It would be valid (however bad form) to have a custom object called 'windows-reg-key` in which case that pattern would be valid.

The [STIX validator](https://github.com/oasis-open/cti-stix-validator) does perform additional checks on the object type and property names. If your pattern is inside a STIX Indicator and you put it through the STIX validator you should get a message about it.
